layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: birkhoff.cheng
  # keybase: your_username
  linkedin: birkhoffcheng
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: birkhoffcheng
  twitter: birkhoffch
  # unsplash: your_username
  # vk: your_username
  website: https://birkhoff.ch/resume.pdf
  youtube: birkhoffcheng

topics:
  - name: Security
    web_url: https://github.com/topics/security
    image_url: https://media.istockphoto.com/photos/anonymous-hacker-with-laptop-in-front-of-binary-code-cyber-security-picture-id962366210?b=1&k=20&m=962366210&s=170667a&w=0&h=DMo_N3cInUGALDSTZ6vhLmKWfDtSUGstb7-dQC-oVcg=

  - name: Systems/Kernel Software Engineering
    web_url: https://github.com/topics/kernel
    image_url: https://media.istockphoto.com/photos/single-corn-kernel-picture-id538372951?k=20&m=538372951&s=612x612&w=0&h=7dvffW6ArPD3ow02Brx1GYvszdTOy1DHnREXieO7O3U=

  - name: Linux Kernel
    web_url: https://www.kernel.org/
    image_url: https://linuxfoundation.org/wp-content/uploads/linux.svg
